
VIA_ENABLE 			= yes
LTO_ENABLE 			= no
TAP_DANCE_ENABLE 	= yes
# KEY_OVERRIDE_ENABLE = yes
ENCODER_MAP_ENABLE	= no		# Enable encoder
BOOTMAGIC_ENABLE 	= no  		# Enable Bootmagic Lite
MOUSEKEY_ENABLE 	= yes		# Mouse keys
EXTRAKEY_ENABLE 	= yes   	# Audio control and System control
CONSOLE_ENABLE 		= no 		# Console for debug
COMMAND_ENABLE 		= no 		# Commands for debug and configuration
# NKRO_ENABLE 		= yes   	# Enable N-Key Rollover - Deprecated
NKRO_DEFAULT_ON     = yes       # Enable N-Key Rollover
BACKLIGHT_ENABLE 	= no   		# Enable keyboard backlight functionality
RGBLIGHT_ENABLE 	= no		# Enable keyboard RGB underglow
AUDIO_ENABLE 		= no   		# Audio output
ENCODER_ENABLE 		= no		# Enable encoder
RGB_MATRIX_ENABLE 	= yes 		# Enable per-key RGB matrix lighting
LEADER_ENABLE = yes
